pub enum Instruction {
    SysAddr(u16),
    Cls,
    Ret,
    JpAddr(u16),
    CallAddr(u16),
    SeVxByte(usize, u8),
    SneVxByte(usize, u8),
    SeVxVy(usize, usize),
    LdVxByte(usize, u8),
    AddVxByte(usize, u8),
    LdVxVy(usize, usize),
    OrVxVy(usize, usize),
    AndVxVy(usize, usize),
    XorVxVy(usize, usize),
    AddVxVy(usize, usize),
    SubVxVy(usize, usize),
    ShrVx(usize),
    SubnVxVy(usize, usize),
    ShlVx(usize),
    SneVxVy(usize, usize),
    LdIAddr(u16),
    JpV0Addr(u16),
    RndVxByte(usize, u8),
    DrwVxVyNibble(usize, usize, u8),
    SkpVx(usize),
    SknpVx(usize),
    LdVxDt(usize),
    LdVxK(usize),
    LdDtVx(usize),
    LdStVx(usize),
    AddIVx(usize),
    LdFVx(usize),
    LdBVx(usize),
    LdIVx(usize),
    LdVxI(usize),
    Unknown(u16), // Used if opcode doesn't match any known instruction
}

pub fn decode(opcode: u16) -> Instruction {
    let addr = opcode & 0x0FFF;
    let nibble = (opcode & 0x000F) as u8;
    let x = ((opcode & 0x0F00) >> 8) as usize;
    let y = ((opcode & 0x00F0) >> 4) as usize;
    let byte = (opcode & 0x00FF) as u8;
    match (opcode & 0xF000) >> 12 {
        0x0 => match opcode & 0x00FF {
            0xE0 => Instruction::Cls,
            0xEE => Instruction::Ret,
            _ => Instruction::SysAddr(addr),
        },
        0x1 => Instruction::JpAddr(addr),
        0x2 => Instruction::CallAddr(addr),
        0x3 => Instruction::SeVxByte(x, byte),
        0x4 => Instruction::SneVxByte(x, byte),
        0x5 => Instruction::SeVxVy(x, y),
        0x6 => Instruction::LdVxByte(x, byte),
        0x7 => Instruction::AddVxByte(x, byte),
        0x8 => match opcode & 0x000F {
            0x0 => Instruction::LdVxVy(x, y),
            0x1 => Instruction::OrVxVy(x, y),
            0x2 => Instruction::AndVxVy(x, y),
            0x3 => Instruction::XorVxVy(x, y),
            0x4 => Instruction::AddVxVy(x, y),
            0x5 => Instruction::SubVxVy(x, y),
            0x6 => Instruction::ShrVx(x),
            0x7 => Instruction::SubnVxVy(x, y),
            0xE => Instruction::ShlVx(x),
            _ => Instruction::Unknown(opcode),
        },
        0x9 => Instruction::SneVxVy(x, y),
        0xA => Instruction::LdIAddr(addr),
        0xB => Instruction::JpV0Addr(addr),
        0xC => Instruction::RndVxByte(x, byte),
        0xD => Instruction::DrwVxVyNibble(x, y, nibble),
        0xE => match opcode & 0x00FF {
            0x9E => Instruction::SkpVx(x),
            0xA1 => Instruction::SknpVx(x),
            _ => Instruction::Unknown(opcode),
        },
        0xF => match opcode & 0x00FF {
            0x07 => Instruction::LdVxDt(x),
            0x0A => Instruction::LdVxK(x),
            0x15 => Instruction::LdDtVx(x),
            0x18 => Instruction::LdStVx(x),
            0x1E => Instruction::AddIVx(x),
            0x29 => Instruction::LdFVx(x),
            0x33 => Instruction::LdBVx(x),
            0x55 => Instruction::LdIVx(x),
            0x65 => Instruction::LdVxI(x),
            _ => Instruction::Unknown(opcode),
        },
        _ => Instruction::Unknown(opcode),
    }
}
